name: 'Build and Push to AWS ECR'
description: 'Builds Docker image and pushes to AWS ECR registry'
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  docker_repo:
    description: 'Docker repository name'
    required: true
  environment:
    description: 'Deployment environment (develop, staging, release)'
    required: true
  image_tag:
    description: 'Image tag (commit SHA or version)'
    required: true
  aws_access_key_id:
    description: 'AWS access key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  ecr_registry:
    description: 'ECR registry URL'
    required: true
  ecr_repo_prefix:
    description: 'ECR repository prefix'
    required: true
  build_args:
    description: 'Docker build arguments (key=value format, one per line or comma-separated)'
    required: false
    default: ''
  context:
    description: 'Docker build context path'
    required: false
    default: '.'
  platforms:
    description: 'Target platforms (e.g., linux/amd64,linux/arm64)'
    required: false
    default: ''
  cache_from:
    description: 'Cache sources (e.g., type=registry,ref=...)'
    required: false
    default: ''
  cache_to:
    description: 'Cache destinations (e.g., type=inline)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Log in to Amazon ECR
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws_region }} | \
        docker login --username AWS --password-stdin ${{ inputs.ecr_registry }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build_args }}
        cache-from: ${{ inputs.cache_from }}
        cache-to: ${{ inputs.cache_to }}
        tags: |
          ${{ inputs.ecr_registry }}/${{ inputs.ecr_repo_prefix }}-${{ inputs.environment }}-${{ inputs.docker_repo }}:latest
          ${{ inputs.ecr_registry }}/${{ inputs.ecr_repo_prefix }}-${{ inputs.environment }}-${{ inputs.docker_repo }}:${{ inputs.image_tag }}
